name: Test

on:
  push:
    branches:
    - main
    paths-ignore:
    - .github/**
  pull_request:
    branches:
    - main
    paths-ignore:
    - .github/**
  workflow_dispatch:

jobs:
  build:
    runs-on: cyclops-k8s-runners
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: azure/setup-helm@v4.3.0
      name: Install Helm
    
    - name: Run tests.sh
      run: |
        sudo apt update
        sudo apt install -y bind9-dnsutils
        ./test.sh
      working-directory: test
      env:
        IS_CI: "1"

    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Test Results
        path: test/results-*.tgz
